stages:
  - build
  - publish
  - update-github-mirror

workflow:
  rules:
    - changes:
      - src/**/*
      - package.json
      - tsconfig.json
      - next.config.ts
      - Dockerfile
      - messages

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "/certs/client"
  only:
    - master
  before_script:
    - apk add --no-cache nodejs npm git
    - git config user.name "gitlab-ci"
    - git config user.email "gitlab-ci@gitlab.com"
  script:
    - DATE_TAG=$(date +v%Y.%m.%d-%H%M)
    - echo "DATE_TAG=$DATE_TAG" >> release.env

    - node makeChangelog.js $DATE_TAG > changelog.md

    - docker build --build-arg VERSION=${DATE_TAG} -t seraphimcms-${DATE_TAG} .
    - docker save seraphimcms-${DATE_TAG} -o seraphimcms-${DATE_TAG}.tar

    - git tag $DATE_TAG
    - git push https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git $DATE_TAG
  artifacts:
    reports:
      dotenv: release.env
    paths:
      - changelog.md
      - seraphimcms-*.tar

publish:
  stage: publish
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  only:
    - master
  dependencies:
    - build
  script:
    - echo "Creating release for ${DATE_TAG}"
  release:
    tag_name: ${DATE_TAG}
    name: 'Release ${DATE_TAG}'
    description: changelog.md
    assets:
      links:
        - name: seraphimcms-${DATE_TAG}.tar
          url: https://${CI_SERVER_HOST}/${CI_PROJECT_PATH}/-/jobs/artifacts/${CI_COMMIT_REF_NAME}/raw/seraphimcms-${DATE_TAG}.tar
          link_type: other

update-github-mirror:
  stage: update-github-mirror
  image:
    name: alpine:latest
    entrypoint: [ "" ]
  only:
    - master
  before_script:
    - apk add --no-cache git
  script:
    - git remote add github https://MomchilKalestrov:${GITHUB_MIRROR_TOKEN}@github.com/MomchilKalestrov/will-power.git
    - git push github HEAD:master --force