stages:
  - generate-tag
  - generate-changelog
  - build-docker-image
  - create-release
  - publish-docker-image
  - update-github-mirror

generate-tag:
  stage: generate-tag
  image: ubuntu:latest
  only:
    - master
  script:
    - DATE_TAG=$(date +v%Y.%m.%d-%H%M)
    - "echo Generated tag: $DATE_TAG"
    - echo "DATE_TAG=$DATE_TAG" > release.env
  artifacts:
    reports:
      dotenv: release.env

generate-changelog:
  stage: generate-changelog
  image: node:latest
  only:
    - master
  script:
    - node makeChangelog.js $DATE_TAG > changelog.md
  artifacts:
    paths:
      - changelog.md

build-docker-image:
  stage: build-docker-image
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "/certs/client"
  dependencies:
    - generate-tag
    - generate-changelog
  only:
    - master
  script:
    - docker build -t seraphimcms-${DATE_TAG} .
    - docker save seraphimcms-${DATE_TAG} -o seraphimcms-${DATE_TAG}.tar
  artifacts:
    paths:
      - seraphimcms-${DATE_TAG}.tar

create-release:
  stage: create-release
  image: ubuntu:latest
  dependencies:
    - build-docker-image
    - generate-tag
    - generate-changelog
  before_script:
    - apt-get update && apt-get install -y git
    - git config user.name "gitlab-ci"
    - git config user.email "gitlab-ci@gitlab.com"
  script:
    - git tag $DATE_TAG
    - git push https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git $DATE_TAG

publish-docker-image:
  stage: publish-docker-image
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  only:
    - master
  script:
    - echo "Creating release for ${DATE_TAG}"
  release:
    tag_name: ${DATE_TAG}
    name: 'Release ${DATE_TAG}'
    description: changelog.md
    assets:
      links:
        - name: seraphimcms-${DATE_TAG}.tar
          url: https://${CI_SERVER_HOST}/${CI_PROJECT_PATH}/-/jobs/artifacts/${CI_COMMIT_REF_NAME}/raw/seraphimcms-${DATE_TAG}.tar
          link_type: other

update-github-mirror:
  stage: update-github-mirror
  image: ubuntu:latest
  only:
    - master
  before_script:
    - apt-get update && apt-get install -y git
  script:
    - git remote add github https://MomchilKalestrov:${GITHUB_MIRROR_TOKEN}@github.com/MomchilKalestrov/will-power.git
    - git push github HEAD:master --force