//@ts-check
export const sampleResponsePage = () => {
    const body =
        '<!DOCTYPE html>\n' +
        '<html lang="en">\n' +
        '<head>\n' +
        '    <meta charset="UTF-8">\n' +
        '    <meta name="viewport" content="width=device-width, initial-scale=1.0">\n' +
        '    <title>Document</title>\n' +
        '</head>\n' +
        '<body>\n' +
        '    <h1>Hello world!</h1>\n' +
        '    <p>This is a response generated by a plugin API route in SeraphimCMS!</p>\n' +
        '</body>\n' +
        '</html>';

    return {
        status: 200,
        headers: {
            'Content-Type': 'text/html',
            'Content-Length': body.length.toString()
        },
        body
    };
};